export const en = {
  "Daily record": "Record daily water intake and track",
  "Water tracker": "Water consumption tracker",
  "Register user": "Try tracker",
  "Login user": "Sign In",
  "Habit drive": "Habit drive",
  "View statistics": "View statistics",
  "Personal rate": " Personal rate setting",
  "Our 1": "Our",
  "Our 2": "customers",
  "Happy customers": "happy",
  "Sign in": "Sign in",
  "Do not": "Don`t have an account?",
  "Register user form": "Sign up",
  "Email user": "Email",
  "Password user": "Password",
  "Enter email": "Enter your email",
  "Enter password": "Enter your password",
  "Already have": "Already have an account?",
  "Repeat password": "Repeat password",
  "Count water": "L",
  "Daily norma": "My daily norma",
  "Today water": "Today",
  "Add water": "Add water",
  "Hello user": "Hello",
  "Water add": "ml",
  "Month water": "Month",
  "Month january": "January",
  "Month february": "February",
  "Month march": "March",
  "Month april": "April",
  "Month may": "May",
  "Month june": "June",
  "Month july": "July",
  "Month august": "August",
  "Month september": "September",
  "Month october": "October",
  "Month november": "November",
  "Month december": "December",
  "Or google": "or",
  "Sign google": "Sign in with Google",
  "Upload avatar": "Upload avatar",
  "Your gender": "Your gender identity",
  "Woman gender": "Woman",
  "Man gender": "Man",
  "Your name": "Your name",
  "Your email": "Your email",
  "Your weight": "Your weight in kilograms:",
  "Time active": "The time of active participation in sports:",
  "Required amount": "The required amount of water in liters per day:",
  "Write down": "Write down how much water you will drink:",
  "Save setting": "Save",
  "Setting user": "Setting",
  "Log out": "Log out",
  "For man": "For man",
  "For woman": "For woman",
  "Water description":
    "V is the volume of the water norm in liters per day, M is your body weight, T is the time of active sports, or another type of activity commensurate in terms of loads (in the absence of these, you must set 0)",
  "Active time": "Active time in hours",
  "Do you really": "Do you really want to leave?",
  "Log exit": "Cancel",
  "Edit amount": "Edit the entered amount of water",
  "Correct entered": "Correct entered data",
  "Amount of water": "Amount of water",
  "Recording time": "Recording time",
  "Enter the value": "Enter the value of the water used",
  "Delete entry": "Delete entry",
  "Your sure": "Are you sure you want to delete the entry?",
  "Delete card": "Delete",
  "Not found": "Not found, please add water",
  "App settings": "App Settings",
  "User settings": "User Settings",
  "Choose your theme": "Choose your theme color",
  "Choose your app": "Choose your app language",
};
