export const ua = {
  "Daily record": "Записуйте щоденне споживання води та відстежуйте",
  "Water tracker": "Трекер споживання води",
  "Register user": "Реєстрація",
  "Login user": "Вхід",
  "Habit drive": "Звичка бути на драйві",
  "View statistics": "Перегляд статистики",
  "Personal rate": "Індивідуальне встановлення тарифу",
  "Our 1": "Наші",
  "Our 2": "користувачі",
  "Happy customers": "сщасливі",
  "Sign in": "Вхід",
  "Do not": "Не маєте облікового запису?",
  "Register user form": "Реєстрація",
  "Email user": "Електронна пошта",
  "Password user": "Пароль",
  "Enter email": "Введіть вашу пошту",
  "Enter password": "Введіть ваш пароль",
  "Already have": "Вже є обліковий запис?",
  "Repeat password": "Повторіть пароль",
  "Count water": "Л",
  "Daily norma": "Моя денна норма",
  "Today water": "Сьогодні",
  "Add water": "Додати воду",
  "Hello user": "Привіт",
  "Water add": "мл",
  "Month water": "Місяць",
  "Month january": "Січень",
  "Month february": "Лютий",
  "Month march": "Березень",
  "Month april": "Квітень",
  "Month may": "Травень",
  "Month june": "Червень",
  "Month july": "Липень",
  "Month august": "Серпень",
  "Month september": "Вересень",
  "Month october": "Жовтень",
  "Month november": "Листопад",
  "Month december": "Грудень",
  "Or google": "або",
  "Sign google": "Увійти за допомогою Google",
  "Upload avatar": "Завантажити аватар",
  "Your gender": "Ваша стать",
  "Woman gender": "Жінка",
  "Man gender": "Чоловік",
  "Your name": `Ваше ім'я`,
  "Your email": "Ваша електронна пошта",
  "Your weight": "Ваша вага в кілограмах:",
  "Time active": "Час активних занять спортом:",
  "Required amount": "Необхідна кількість води в літрах на добу:",
  "Write down": "Запишіть, скільки води ви будете пити:",
  "Save setting": "Зберегти",
  "Setting user": "Налаштування",
  "Log out": "Вихід",
  "For man": "Для чоловіків",
  "For woman": "Для жінок",
  "Water description":
    "V – об’єм води норма в літрах на добу, М – маса вашого тіла, Т – час активності спорт, або інший вид діяльності, відповідний за навантаженнями (в відсутність цих, ви повинні встановити 0)",
  "Active time": "Час активності в годинах",
  "Do you really": "Ти справді хочеш піти?",
  "Log exit": "Відмінити",
  "Edit amount": "Відредагуйте введену кількість води",
  "Correct entered": "Правильно введені дані",
  "Amount of water": "Кількість води",
  "Recording time": "Час запису",
  "Enter the value": "Введіть вартість використаної води",
  "Delete entry": "Видалити запис",
  "Your sure": "Ви впевнені, що хочете видалити запис?",
  "Delete card": "Видалити",
  "Not found": "Не знайдено, додайте води",
  "App settings": "Налаштування додатку",
  "User settings": "Налаштуванні користувача",
  "Choose your theme": "Виберіть колір теми",
  "Choose your app": "Виберіть мову додатку",
};
